USE [master]
GO

/****** Object:  Database [OrderSystem] ******/
CREATE DATABASE [OrderSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OrderSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\OrderSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OrderSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\OrderSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )

GO
ALTER DATABASE [OrderSystem] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrderSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OrderSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OrderSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OrderSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OrderSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OrderSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [OrderSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OrderSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OrderSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OrderSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OrderSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OrderSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OrderSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OrderSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OrderSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OrderSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OrderSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OrderSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OrderSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OrderSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OrderSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OrderSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OrderSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OrderSystem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OrderSystem] SET  MULTI_USER 
GO
ALTER DATABASE [OrderSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OrderSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OrderSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OrderSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OrderSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OrderSystem] SET QUERY_STORE = OFF
GO

USE [OrderSystem]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menu](
	[MenuID] [int] NOT NULL,
	[ProductName] [varchar](50) NOT NULL,
	[ProductType] [varchar](50) NOT NULL,
	[ProductCategory] [varchar](50) NOT NULL,
	[ProductID] [int] NOT NULL
 CONSTRAINT [PK_Menu] PRIMARY KEY CLUSTERED 
(
	[MenuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

drop table ProductCategory
CREATE TABLE [dbo].[ProductCategory](
	[PCID] [int] NOT NULL,
	[ProductCategoryName] [varchar](50) NOT NULL
 CONSTRAINT [PK_ProductCategory] PRIMARY KEY CLUSTERED 
(
	[PCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[Product](
	[PID] [int] NOT NULL,
	[ProductName] [varchar](50) NOT NULL,
	[ProductType] [varchar](50) NOT NULL,
	[ProductCategory] [varchar](50) NOT NULL,
	[Price] [Decimal] (5,2) NOT NULL,
	[CategoryID] [int] NOT NULL
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[Costumer](
	[CID] [int] NOT NULL,
	[FirstName] [varchar](20) NOT NULL,
	[LastType] [varchar](20) NOT NULL,
	[BillingAddress] [varchar](50) NOT NULL,
	[Phone] [char](12) NOT NULL,
	[Description] [varchar](50) NOT NULL
 CONSTRAINT [PK_Costumer] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[Invoice](
	[IVID] [int] NOT NULL,
	[InvoiceNumber] [varchar](50) NOT NULL,
	[OrderNumber] [varchar](50) NOT NULL,
	[CostumerName] [varchar](50) NOT NULL,
	[InvoiceDate] [date] NOT NULL,
	[InvoiceTotal] [Decimal] (6,2) NOT NULL,
	[BillingAddress] [varchar](50) NOT NULL,
	[EmployeeName] [varchar](50) NOT NULL,
	[CostumerID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[OrderID] [int] NOT NULL 
 CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED 
(
	[IVID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[Order](
	[OID] [int] NOT NULL,
	[OrderName] [varchar](50) NOT NULL,
	[OrderNumber] [char](3) NOT NULL,
	[OrderTotal] [Decimal](6,2) NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[EmployeeName] [varchar](50) NOT NULL,
	[ProductID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[OID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[Employee](
	[EID] [int] NOT NULL,
	[EmployeeName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[EID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT [dbo].[Menu] ([FloorID], [Floor Description]) VALUES (1, N'Hardwood')
INSERT [dbo].[Menu] ([FloorID], [Floor Description]) VALUES (2, N'Ceramic')
INSERT [dbo].[Menu] ([FloorID], [Floor Description]) VALUES (3, N'Laminate')
INSERT [dbo].[Menu] ([FloorID], [Floor Description]) VALUES (4, N'Linoleum')

USE [master]
GO

ALTER DATABASE [OrderSystem] SET  READ_WRITE 
GO
